config/routes.rb
InsuranceClient::Application.routes.draw do
  devise_for :users

  resources :user_profiles, only: [:edit, :update]

  resources :policies do
    collection do
      get 'synchronize'
    end
  end

  resources :cars do
    collection do
      get 'synchronize'
    end
  end

  resources :car_models, only: [:show, :index] do
    collection do
      get 'synchronize'
    end
  end

  resources :clients do
    collection do
      get 'synchronize'
    end
  end

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  include Savon::Model
  document "http://localhost:8080/ClientsWebservice/ClientsWebservice?WSDL"

  validates :first_name, :last_name, :address, :city, :postcode, :pesel, :gender, :birth_date, presence: true
  validates :pesel, uniqueness: true

  has_many :policies, dependent: :destroy

  state_machine :state, initial: :unsynchronized do
  	event :sync_completed do
      transition [:unsynchronized] => :synchronized
  	end

    event :local_modification do
      transition [:unsynchronized, :synchronized] => :unsynchronized
    end
  end

  def full_name
    "#{first_name} #{last_name} PESEL #{pesel}"
  end

  def self.synchronize_all
    Client.find_each { |client| client.synchronize }
  end

  def synchronize
    client_data = find_soap_request
    if client_data
      update_soap_request
    else
      create_soap_request
    end
    self.sync_completed
  end

  private
  def find_soap_request
    response = client.request(:ns2, :find_client_by_pesel) do |soap|
      soap.body = { pesel: pesel }
    end
    response[:find_client_by_pesel_response][:return]
  end
  def create_soap_request
    response = client.request(:ns2, :create_client) do |soap|
      soap.body = soap_request_parameters
    end
    response[:create_client_response][:return]
  end

  def update_soap_request
    response = client.request(:ns2, :update_client) do |soap|
      soap.body = soap_request_parameters
    end
    response[:update_client_response][:return]
  end

  def soap_request_parameters
    { first_name: first_name,
      last_name: last_name,
      address: address,
      city: city,
      postcode: postcode,
      pesel: pesel,
      gender: gender,
      birth_date: birth_date,
      license_number: license_number,
      updated_at: updated_at
    }
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!
  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        @client.local_modification
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end

  def synchronize
    Client.synchronize_all
    redirect_to clients_path
  end
end

app/views/clients/_form.html.haml
= semantic_form_for @client do |f|
  -if @client.errors.any?
    #error_explanation
      %h2= "#{pluralize(@client.errors.count, "error")} prohibited this client from being saved:"
      %ul
        - @client.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :first_name
  .field
    = f.input :last_name
  .field
    = f.input :address
  .field
    = f.input :city
  .field
    = f.input :postcode
  .field
    = f.input :pesel
  .field
    = f.input :gender
  .field
    = f.input :birth_date, start_year: 1900, end_year: Date.today.year
  .field
    = f.input :license_number
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/clients/edit.html.haml
%h1 Editing client

= render 'form'

= link_to 'Show', @client, class: 'btn'
= link_to 'Back', clients_path, class: 'btn'

app/views/clients/index.html.haml
%h1 Listing clients

%table
  %tr
    %th First name
    %th Last name
    %th Address
    %th City
    %th Postcode
    %th Pesel
    %th Gender
    %th Birth date
    %th License number
    %th State
    %th
    %th
    %th

  - @clients.each do |client|
    %tr
      %td= client.first_name
      %td= client.last_name
      %td= client.address
      %td= client.city
      %td= client.postcode
      %td= client.pesel
      %td= client.gender
      %td= client.birth_date
      %td= client.license_number
      %td{ class: (client.synchronized? ? 'synchronized' : 'unsynchronized') }= client.state
      %td= link_to 'Show', client, class: 'btn'
      %td= link_to 'Edit', edit_client_path(client), class: 'btn'
      %td= link_to 'Destroy', client, :confirm => 'Are you sure?', :method => :delete, class: 'btn'

%br

= link_to 'New Client', new_client_path, class: 'btn btn-primary'
= link_to 'Synchronize', synchronize_clients_path, class: 'btn btn-danger'

app/views/clients/new.html.haml
%h1 New client

= render 'form'

= link_to 'Back', clients_path, class: 'btn'

app/views/clients/show.html.haml
%p
  %b First name:
  = @client.first_name
%p
  %b Last name:
  = @client.last_name
%p
  %b Address:
  = @client.address
%p
  %b City:
  = @client.city
%p
  %b Postcode:
  = @client.postcode
%p
  %b Pesel:
  = @client.pesel
%p
  %b Gender:
  = @client.gender
%p
  %b Birth date:
  = @client.birth_date
%p
  %b License number:
  = @client.license_number

%p
  %b State:
  %span{ class: (@client.synchronized? ? 'synchronized' : 'unsynchronized') }= @client.state

= link_to 'Edit', edit_client_path(@client), class: 'btn'
= link_to 'Back', clients_path, class: 'btn'