config/routes.rb
InsuranceClient::Application.routes.draw do
  devise_for :users

  resources :user_profiles, only: [:edit, :update]

  resources :policies do
    collection do
      get 'synchronize'
    end
  end

  resources :cars do
    collection do
      get 'synchronize'
    end
  end

  resources :car_models, only: [:show, :index] do
    collection do
      get 'synchronize'
    end
  end

  resources :clients do
    collection do
      get 'synchronize'
    end
  end

  root :to => 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  include Savon::Model
  document "http://localhost:8080/CarsWebService/CarsWebService?WSDL"

  belongs_to :car_model
  validates :car_model, :vin, :plates_number, :date_of_manufacture, presence: true
  validates :vin, uniqueness: true

  has_many :policies, dependent: :destroy

  state_machine :state, initial: :unsynchronized do
  	event :sync_completed do
      transition [:unsynchronized] => :synchronized
  	end

    event :local_modification do
      transition [:unsynchronized, :synchronized] => :unsynchronized
    end
  end

  def full_name
    "#{car_model_full_name} VIN: #{vin}"
  end

  def model_price
    car_model.price
  end

  def car_model_name
  	car_model.name
  end

  def car_model_manufacture_year
    car_model.manufacture_year
  end

  def car_model_full_name
    car_model.full_name
  end

  def self.synchronize_all
    Car.find_each { |car| car.synchronize }
  end

  def synchronize
    car_data = find_soap_request
    if car_data
      update_soap_request
    else
      create_soap_request
    end
    self.sync_completed
  end

  private
  def find_soap_request
    response = client.request(:ns2, :find_car_by_vin) do |soap|
      soap.body = { vin: vin }
    end
    response[:find_car_by_vin_response][:return]
  end
  def create_soap_request
    response = client.request(:ns2, :create_car) do |soap|
      soap.body = soap_request_parameters
    end
    response[:create_car_response][:return]
  end

  def update_soap_request
    response = client.request(:ns2, :update_car) do |soap|
      soap.body = soap_request_parameters
    end
    response[:update_car_response][:return]
  end

  def soap_request_parameters
    { car_model_name: car_model_name,
      car_model_manufacture_year: car_model_manufacture_year,
      vin: vin,
      plates_number: plates_number,
      date_of_manufacture: date_of_manufacture,
      updated_at: updated_at
    }
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :authenticate_user!
  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])

    respond_to do |format|
      if @car.update_attributes(params[:car])
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end

  def synchronize
    Car.synchronize_all
    redirect_to cars_path
  end
end

app/views/cars/_form.html.haml
= semantic_form_for @car do |f|
  -if @car.errors.any?
    #error_explanation
      %h2= "#{pluralize(@car.errors.count, "error")} prohibited this car from being saved:"
      %ul
        - @car.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :car_model
  .field
    = f.input :vin, as: :string
  .field
    = f.input :plates_number
  .field
    = f.input :date_of_manufacture, as: :date_select, start_year: 1900, end_year: Date.today.year

  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/cars/edit.html.haml
%h1 Editing car

= render 'form'

= link_to 'Show', @car, class: 'btn'
= link_to 'Back', cars_path, class: 'btn'

app/views/cars/index.html.haml
%h1 Listing cars

%table
  %tr
    %th Car model
    %th Vin
    %th Plates number
    %th Date of manufacture
    %th State
    %th
    %th
    %th

  - @cars.each do |car|
    %tr
      %td= car.car_model_full_name
      %td= car.vin
      %td= car.plates_number
      %td= car.date_of_manufacture
      %td{ class: (car.synchronized? ? 'synchronized' : 'unsynchronized') }= car.state
      %td= link_to 'Show', car, class: 'btn'
      %td= link_to 'Edit', edit_car_path(car), class: 'btn'
      %td= link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete, class: 'btn'

%br

= link_to 'New Car', new_car_path, class: 'btn btn-primary'
= link_to 'Synchronize', synchronize_cars_path, class: 'btn btn-danger'

app/views/cars/new.html.haml
%h1 New car

= render 'form'

= link_to 'Back', cars_path, class: 'btn'

app/views/cars/show.html.haml
%p
  %b Car model:
  = @car.car_model_full_name
%p
  %b Vin:
  = @car.vin
%p
  %b Plates number:
  = @car.plates_number
%p
  %b Date of manufacture:
  = @car.date_of_manufacture
%p
  %b State:
  %span{ class: (@car.synchronized? ? 'synchronized' : 'unsynchronized') }= @car.state

= link_to 'Edit', edit_car_path(@car), class: 'btn'
= link_to 'Back', cars_path, class: 'btn'