config/routes.rb
InsuranceClient::Application.routes.draw do
  devise_for :users

  resources :user_profiles, only: [:edit, :update]

  resources :policies do
    collection do
      get 'synchronize'
    end
  end

  resources :cars do
    collection do
      get 'synchronize'
    end
  end

  resources :car_models, only: [:show, :index] do
    collection do
      get 'synchronize'
    end
  end

  resources :clients do
    collection do
      get 'synchronize'
    end
  end

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from Errno::ECONNREFUSED, with: :connection_refused
  
  def connection_refused
  	flash[:error] = 'Could not connect to external server!'
  	redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_navbar.html.haml
.navbar
  .navbar-inner
    .container
      %ul.nav
        %li= link_to 'Clients', clients_path
        %li= link_to 'Car models', car_models_path
        %li= link_to 'Cars', cars_path
        %li= link_to 'Policies', policies_path
        %li= link_to 'Profile', edit_user_profile_path(current_user.id) if current_user.present?
        %li= link_to 'Logout', destroy_user_session_path, method: 'DELETE' if current_user.present?

app/views/application/_notifications.html.haml
%span.flash
  - if flash.present?
    - flash.each do |message_type, message|
      %p{ class: message_type }= message