config/routes.rb
InsuranceClient::Application.routes.draw do
  devise_for :users

  resources :user_profiles, only: [:edit, :update]

  resources :policies do
    collection do
      get 'synchronize'
    end
  end

  resources :cars do
    collection do
      get 'synchronize'
    end
  end

  resources :car_models, only: [:show, :index] do
    collection do
      get 'synchronize'
    end
  end

  resources :clients do
    collection do
      get 'synchronize'
    end
  end

  root :to => 'home#index'

end

app/models/policy.rb
class Policy < ActiveRecord::Base
  include Savon::Model
  document "http://localhost:8080/PolicyWebService/PolicyWebService?WSDL"

  NEW_CAR_RATE = 0.05
  UP_PER_YEAR_RATE = 0.003
  MAXIMAL_RATE = 0.15

  belongs_to :owner, class_name: 'Client', foreign_key: 'client_id'
  belongs_to :agent, class_name: 'User', foreign_key: 'agent_id'
  belongs_to :car

  validates :client_id, :car_id, presence: true
  validates :policy_number, uniqueness: true

  before_create :generate_policy_number
  before_save :calculate_total_price

  state_machine :state, initial: :unsynchronized do
    event :sync_completed do
      transition [:unsynchronized] => :synchronized
    end

    event :local_modification do
      transition [:unsynchronized, :synchronized] => :unsynchronized
    end
  end

  def full_agent_name
    agent.try(:full_name)
  end

  def car_full_name
    "#{car.full_name}"
  end

  def client_full_name
    "#{owner.first_name} #{owner.last_name}"
  end

  def client_pesel
    owner.pesel
  end

  def car_vin
    car.vin
  end

  def self.synchronize_all
    Policy.find_each { |policy| policy.synchronize }
  end

  def synchronize
    owner.synchronize
    car.synchronize
    policy_data = find_soap_request

    if policy_data
      update_soap_request
    else
      create_soap_request
    end
    self.sync_completed
  end

  private
  def find_soap_request
    response = client.request(:ns2, :find_policy_by_policy_number) do |soap|
      soap.body = { policy_number: policy_number }
    end
    response[:find_policy_by_policy_number_response][:return]
  end
  def create_soap_request
    response = client.request(:ns2, :create_policy) do |soap|
      soap.body = soap_request_parameters
    end
    response[:create_policy_response][:return]
  end

  def update_soap_request
    response = client.request(:ns2, :update_policy) do |soap|
      soap.body = soap_request_parameters
    end
    response[:update_policy_response][:return]
  end

  def soap_request_parameters
    { policy_number: policy_number,
      total_price: total_price,
      client_pesel: client_pesel,
      car_vin: car_vin,
      updated_at: updated_at
    }
  end

  def generate_policy_number
    self.policy_number = "AA#{Time.now.to_i}"
  end

  def calculate_total_price
    rate = (NEW_CAR_RATE + UP_PER_YEAR_RATE * car_age)
    rate = MAXIMAL_RATE if rate > MAXIMAL_RATE
    self.total_price = rate * car_model_price
  end

  def car_model_price
    car.model_price
  end

  def car_age
    Time.diff(Date.today, car.date_of_manufacture)[:year]
  end
end

app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_filter :authenticate_user!
  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @policies }
    end
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
    @policy = Policy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @policy }
    end
  end

  # GET /policies/new
  # GET /policies/new.json
  def new
    @policy = Policy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @policy }
    end
  end

  # GET /policies/1/edit
  def edit
    @policy = Policy.find(params[:id])
  end

  # POST /policies
  # POST /policies.json
  def create
    @policy = Policy.new(params[:policy].merge(agent_id: current_user.id))

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render json: @policy, status: :created, location: @policy }
      else
        format.html { render action: "new" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /policies/1
  # PUT /policies/1.json
  def update
    @policy = Policy.find(params[:id])

    respond_to do |format|
      if @policy.update_attributes(params[:policy])
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy = Policy.find(params[:id])
    @policy.destroy

    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :no_content }
    end
  end

  def synchronize
    Policy.synchronize_all
    redirect_to policies_path
  end
end

app/helpers/policies_helper.rb
module PoliciesHelper
end

app/views/policies/_form.html.haml
= semantic_form_for @policy do |f|
  -if @policy.errors.any?
    #error_explanation
      %h2= "#{pluralize(@policy.errors.count, "error")} prohibited this policy from being saved:"
      %ul
        - @policy.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.input :car
  .field
    = f.input :owner
  .actions
    = f.submit 'Save', class: 'btn btn-primary'

app/views/policies/edit.html.haml
%h1 Editing policy

= render 'form'

= link_to 'Show', @policy, class: 'btn'
= link_to 'Back', policies_path, class: 'btn'

app/views/policies/index.html.haml
%h1 Listing policies

%table
  %tr
    %th.wide Car
    %th Client
    %th Policy number
    %th Total price
    %th Agent
    %th Date
    %th State
    %th
    %th
    %th

  - @policies.each do |policy|
    %tr
      %td.wide= policy.car_full_name
      %td= policy.client_full_name
      %td= policy.policy_number
      %td= policy.total_price
      %td= policy.full_agent_name
      %td= policy.created_at.strftime("%d-%m-%Y")
      %td{ class: (policy.synchronized? ? 'synchronized' : 'unsynchronized') }= policy.state
      %td= link_to 'Show', policy, class: 'btn'
      %td= link_to 'Edit', edit_policy_path(policy), class: 'btn'
      %td= link_to 'Destroy', policy, confirm: 'Are you sure?', method: :delete, class: 'btn'

%br

= link_to 'New Policy', new_policy_path, class: 'btn btn-primary'
= link_to 'Synchronize', synchronize_policies_path, class: 'btn btn-danger'

app/views/policies/new.html.haml
%h1 New policy

= render 'form'

= link_to 'Back', policies_path, class: 'btn'

app/views/policies/show.html.haml
%p#notice= notice

%p
  %b Car:
  = @policy.car_full_name
%p
  %b Owner:
  = @policy.client_full_name
%p
  %b Policy number:
  = @policy.policy_number
%p
  %b Total price:
  = @policy.total_price
%p
  %b Agent:
  = @policy.full_agent_name

%p
  %b State:
  %span{ class: (@policy.synchronized? ? 'synchronized' : 'unsynchronized') }= @policy.state

= link_to 'Edit', edit_policy_path(@policy), class: 'btn'
= link_to 'Delete', @policy, confirm: 'Are you sure?', method: :delete, class: 'btn'
= link_to 'Back', policies_path, class: 'btn'